#!/bin/bash

# Wrapper to allow docker invocations that request a TTY to run in non-TTY CI
# environments. When stdin is not a TTY, drop the `-t` flag (or the `-it`/`-ti`
# combination) so commands like run-in-docker.sh can execute successfully.
args=()
stdin_is_tty=0
if [ -t 0 ]; then
    stdin_is_tty=1
fi

for arg in "$@"; do
    case "$arg" in
        -it|-ti)
            if [ "$stdin_is_tty" -eq 1 ]; then
                args+=("$arg")
            else
                args+=("-i")
            fi
            ;;
        -t|--tty)
            if [ "$stdin_is_tty" -eq 1 ]; then
                args+=("$arg")
            fi
            ;;
        *)
            args+=("$arg")
            ;;
    esac
done

exec /usr/local/bin/docker "${args[@]}"
